# Generated by Django 3.1.1 on 2020-11-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectiontable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirconditioningList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirconditioningListname', models.CharField(max_length=100, verbose_name='空调列表')),
            ],
        ),
        migrations.RemoveField(
            model_name='airconditioning',
            name='AirconditioningListname',
        ),
        migrations.AddField(
            model_name='airconditioning',
            name='Airconditioning_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Inspectiontable.airconditioninglist'),
            preserve_default=False,
        ),
    ]
